### ISSUE TITLE
Download for Linux

### ISSUE THREAD

**Issue by probonopd** [lmcapacho/SimDSP#1]
Is there an AppImage download for Linux?

**Comment by lmcapacho** [comment]
There is not an AppImage download for Linux in this moment.

**Comment by probonopd** [comment]
Please consider to upload the AppImage to the GitHub Releases page of this project.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by lmcapacho** [comment]
There is an AppImage to the GitHub Releases page of this project.

Thank you.

**Comment by probonopd** [comment]
Getting

```
SimDSP: error while loading shared libraries: libpulse-mainloop-glib.so.0: cannot open shared object file: No such file or directory
```

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/331329604#L586

**Comment by lmcapacho** [comment]
There is a new update to the AppImage of this project

**Comment by probonopd** [comment]
Still seems to have this issue:
https://travis-ci.org/AppImage/appimage.github.io/builds/331592843#L587

**Comment by lmcapacho** [comment]
https://travis-ci.org/AppImage/appimage.github.io/jobs/332123120#

**Comment by probonopd** [comment]
Thank you very much. Added to the [AppImageHub](https://appimage.github.io/apps/) central directory of available AppImages.

**Comment by lmcapacho** [comment]
Thank you so much.
